// Generated by Proteus Visual Designer for Arduino

// Peripheral Configuration Code (Do Not Edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")

#include <core.h> // Required by cpu
#include <cpu.h>
#include <spi.h> // Required by LCD1
#include <wire.h> // Required by LCD1
#include <GFX_Display.h>
#include <DHTxx.h>
#include <Generic.h>

#pragma GCC pop_options

// Peripheral Constructors
CPU &io_cpu = Cpu;
GFX_Display<Grove_SSD1308> io_LCD1 = GFX_Display<Grove_SSD1308> ();
DHTXX io_HTS1 = DHTXX (8, 22);
GenericInputVoltage io_VIN1 = GenericInputVoltage (A0);
GenericInputVoltage io_VIN2 = GenericInputVoltage (A1);
GenericInputVoltage io_VIN3 = GenericInputVoltage (A2);

void peripheral_setup () {
 io_LCD1.begin (2);
 io_HTS1.begin ();
}

void peripheral_loop() {
}
//---CONFIG_END---
// Flowchart Variables
float var_t;
float var_h;
String var_message;
float var_Volt;
float var_volt2;
float var_volt3;

// Flowchart Routines
void chart_SETUP() {
 io_cpu.setBuiltInLED(false);
}

void chart_LOOP() {
 var_t=io_HTS1.readTemperature(0);
 var_h=io_HTS1.readHumidity();
 var_Volt=io_VIN1.readVoltage();
 var_volt2=io_VIN2.readVoltage();
 var_volt3=io_VIN3.readVoltage();
 var_message="Moisture:"+toString(var_t)+"\npH:"+toString(var_h)+"\n\nN:"+toString(var_Volt)+"\nP:"+toString(var_volt2)+"\nK:"+toString(var_volt3)+"\n\nvisit farmers.org ";
 chart_LCD();
 io_cpu.setBuiltInLED(true);
}

void chart_LCD() {
 io_LCD1.clearDisplay();
 io_LCD1.setTextColor(1);
 io_LCD1.setTextSize(1);
 io_LCD1.setCursor(0,0);
 io_LCD1.print().arg(var_message).end();
 io_LCD1.display();
}

// Entry Points and Interrupt Handlers
void setup () { peripheral_setup();  chart_SETUP(); }
void loop () { peripheral_loop();  chart_LOOP(); }
